### ISSUE TITLE
Site redirect

### ISSUE THREAD

**Issue by karbassi** [todotxt/todotxt.github.io#2]
@ginatrapani I've moved over the `gh-pages` from the `todotxt-cli` project into this repo. The CNAME points to `todotxt.com`.

Next step is to have the domain to point to GitHub servers.

https://help.github.com/articles/setting-up-an-apex-domain/#configuring-an-alias-or-aname-record-with-your-dns-provider

**Comment by ginatrapani** [comment]
Thanks for doing that @karbassi! I made the changes to the domain configuration today, but the DNS needs some time to propagate. I'll check back in tomorrow and close this issue once I've confirmed it's working.

**Comment by ginatrapani** [comment]
Forgot to mention: I own todotxt.com as well as todotxt.org. The .org just forwards to .com right now, but it's available to us if we want to use it differently at any point in the future.

**Comment by karbassi** [comment]
@ginatrapani Idea, how about doing the reverse since the project has moved to an org. Having [todotxt.com](http://todotxt.com) redirect to [todotxt.org](http://todotxt.org) (which points to this repo)

**Comment by ginatrapani** [comment]
>  Idea, how about doing the reverse since the project has moved to an org. Having todotxt.com redirect to todotxt.org (which points to this repo)

Yep, I think that's a good idea. I'll PR the CNAME update, and when that's merged I'll update the DNS config.

**Comment by ginatrapani** [comment]
Also there's the Tumblr blog located at http://blog.todotxt.com/

I can make this blog.todotxt.org when we make this switch.

**Comment by karbassi** [comment]
@ginatrapani all sounds good. The CNAME is merged and we wait for DNS to propagate. 

Close this issue when https://dnschecker.org/#A/todotxt.com and https://dnschecker.org/#A/todotxt.org are working.

**Comment by ginatrapani** [comment]
Okay, I've updated the DNS config. todotxt.org is resolving but the forward from todotxt.com -> todotxt.org is taking longer. I'll keep an eye on it, and leave this open until I've confirmed it's working.

**Comment by karbassi** [comment]
I just checked the DNS propagation and it's propagated across the world. Closing.
