### ISSUE TITLE
[Homepage] add Clockwork Tomato to TODO.txt compatible apps.

### ISSUE THREAD

**Issue by karbassi** [todotxt/todotxt.github.io#5]
_From @timoc on February 21, 2017 16:45_

[Clockwork Tomato](https://play.google.com/store/apps/details?id=net.phlam.android.clockworktomato&hl=en) the fantastic (IMHO) pomodoro tool for Android has been supporting todo.txt integration (with sync via dropbox) for a while now. 

It supports multiple profiles with separate todo.txt files, so I use it to work through my personal and family todo.txt files.

I didn't see it mentioned on the homepage so created an issue for it, for those who want their pomodoro's in todo.txt flavor.

Full disclosure: I suggested the feature to the developers way back when - which is my only relationship with them.

_Copied from original issue: todotxt/todo.txt-cli#200_

**Comment by timoc** [comment]
HI It still seems to be missing from the list.

**Comment by karbassi** [comment]
Hello @timoc, thanks for bringing this up to our attention.

Could you submit a pull request with the link update? We can merge it right away. Be sure to reference this issue. :)

👍
