### ISSUE TITLE
Replace the Yahoo Groups mailing list?

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todotxt.github.io#8]
The community needs a place to reach out for support, announce new Todo.txt projects, report bugs, and ask questions that doesn't require a GitHub login. Is there another mailing list or forum we'd prefer to move to? Yahoo Groups is very old and crusty.

**Comment by karbassi** [comment]
Thoughts:

- Google Groups is as old and crusty. Voting 👎  on that.
- [Discourse offers free hosting](https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/). Voting 👍 for that for now.

Would love to produce a list of options before deciding on something.

**Comment by vorburger** [comment]
Google Groups isn't all that bad ;-)

Dunno if Discourse has old style mailing list "subscribe" type usage? I think that's key.

Oh an https://gitter.im is pretty neat - maybe that's actually even enough, for now?

**Comment by karbassi** [comment]
Since Yahoo Groups is dead and the website url has been updated to use gitter, I'm marking this fixed for now.
